---
# This role contains tasks for configuring and starting netmaster and netplugin service
- name: check dns container image
  shell: docker inspect skynetservices/skydns
  register: docker_inspect_result
  ignore_errors: yes

- name: pull dns container image
  shell: docker pull skynetservices/skydns
  when: "'No such image' in docker_inspect_result.stderr"

- include: deploy_binaries.yml
  when: contiv_demo 
