---
# This role contains tasks for install base packages

- name: upgrade system (debian)
  apt:
    update_cache: true
    name: '*'
    state: latest
  when: ansible_os_family == "Debian"

- name: upgrade system (redhat)
  yum:
    update_cache: true
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: install base packages (debian)
  apt:
    name: "{{ item }}"
  with_items:
    - unzip
    - vim-nox
    - curl
    - python-software-properties
    - git 
    - mercurial
    - build-essential
    - perl
    - librbd-dev
    - lshw
    - python-pip
  when: ansible_os_family == "Debian"

# install epel-release first to ensure the extra packages can be installed later
- name: install epel release package (redhat)
  yum:
    name: epel-release
  when: ansible_os_family == "RedHat"

- name: install base packages (redhat)
  yum:
    name: "{{ item }}"
  with_items:
    - ntp
    - unzip
    - vim
    - curl
    - git
    - mercurial
    - gcc
    - perl
    - librbd1-devel
    - lshw
    - python-pip
    - python-requests # XXX required by ceph repo, but it has a bad package on it
  when: ansible_os_family == "RedHat"

- name: install and start ntp
  shell: systemctl enable ntpd
  when: ansible_os_family == "RedHat"

- name: download consul binary 
  get_url: 
    validate_certs: no
    url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
    dest: /tmp/consul.zip

- name: install consul
  shell: "chdir=/tmp creates=/usr/bin/consul unzip /tmp/consul.zip && mv /tmp/consul /usr/bin"

- name: install ansible (redhat)
  yum: name=ansible state=present
  when: ansible_os_family == "RedHat"

- name: add ansible apt repository (debian)
  apt_repository: repo=ppa:ansible/ansible state=present
  when: ansible_os_family == "Debian"

- name: install ansible (debian)
  apt: name=ansible state=present
  when: ansible_os_family == "Debian"

#NOTE: Upgrade pip to latest which is needed for correct installation of docker-compose
#XXX: This messes with the python packages already installed causing any yum/apt
#re-run to fail subsequently. We need a different way to update pip.
- name: upgrade pip
  pip:
    name: pip
    extra_args: "--upgrade"

#- name: setup systemd files for services
#  copy: src=files/{{ item }} dest=/etc/default/{{ item }}
#  with_items:
#    - consul
#- name: setup systemd units for services
#  copy: src=files/{{ item }}.service dest=/etc/systemd/system/{{ item }}.service
#  with_items:
#    - volmaster 
#    - volplugin
#    - consul
# - name: start the services
#   shell: systemctl daemon-reload
