- name: upgrade system (debian)
  apt:
    update_cache: true
    state: latest

- name: install base packages (debian)
  apt:
    name: "{{ item }}"
  with_items:
    - unzip
    - bzip2
    - curl
    - python-software-properties
    - librbd-dev
    - lshw
    - bash-completion

- name: add ansible apt repository (debian)
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    validate_certs: "{{ validate_certs }}"

- name: install ansible (debian)
  apt: name=ansible state=latest
